[package]
name = "p5"
description = "A tui client for Pulumi"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
homepage = "https://github/rfhold/p5"
repository = "https://github/rfhold/p5"

[dependencies]
bollard = "0.18.1"
clap = { version = "4.5.32", features = ["derive", "env"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
directories = "6.0.0"
glob = "0.3.2"
lazy_static = "1.5.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
strum = { version = "0.27.1", features = ["derive"] }
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
walkdir = "2.5.0"
