// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/plugins/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthPlugin_Authenticate_FullMethodName = "/p5.plugin.v0.AuthPlugin/Authenticate"
)

// AuthPluginClient is the client API for AuthPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthPlugin provides authentication capabilities
type AuthPluginClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthPluginClient(cc grpc.ClientConnInterface) AuthPluginClient {
	return &authPluginClient{cc}
}

func (c *authPluginClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, AuthPlugin_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthPluginServer is the server API for AuthPlugin service.
// All implementations must embed UnimplementedAuthPluginServer
// for forward compatibility.
//
// AuthPlugin provides authentication capabilities
type AuthPluginServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	mustEmbedUnimplementedAuthPluginServer()
}

// UnimplementedAuthPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthPluginServer struct{}

func (UnimplementedAuthPluginServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAuthPluginServer) mustEmbedUnimplementedAuthPluginServer() {}
func (UnimplementedAuthPluginServer) testEmbeddedByValue()                    {}

// UnsafeAuthPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthPluginServer will
// result in compilation errors.
type UnsafeAuthPluginServer interface {
	mustEmbedUnimplementedAuthPluginServer()
}

func RegisterAuthPluginServer(s grpc.ServiceRegistrar, srv AuthPluginServer) {
	// If the following call pancis, it indicates UnimplementedAuthPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthPlugin_ServiceDesc, srv)
}

func _AuthPlugin_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthPlugin_ServiceDesc is the grpc.ServiceDesc for AuthPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p5.plugin.v0.AuthPlugin",
	HandlerType: (*AuthPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthPlugin_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugins/proto/plugin.proto",
}

const (
	ImportHelperPlugin_GetImportSuggestions_FullMethodName = "/p5.plugin.v0.ImportHelperPlugin/GetImportSuggestions"
)

// ImportHelperPluginClient is the client API for ImportHelperPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ImportHelperPlugin provides import ID suggestions (optional capability)
type ImportHelperPluginClient interface {
	GetImportSuggestions(ctx context.Context, in *ImportSuggestionsRequest, opts ...grpc.CallOption) (*ImportSuggestionsResponse, error)
}

type importHelperPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewImportHelperPluginClient(cc grpc.ClientConnInterface) ImportHelperPluginClient {
	return &importHelperPluginClient{cc}
}

func (c *importHelperPluginClient) GetImportSuggestions(ctx context.Context, in *ImportSuggestionsRequest, opts ...grpc.CallOption) (*ImportSuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSuggestionsResponse)
	err := c.cc.Invoke(ctx, ImportHelperPlugin_GetImportSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportHelperPluginServer is the server API for ImportHelperPlugin service.
// All implementations must embed UnimplementedImportHelperPluginServer
// for forward compatibility.
//
// ImportHelperPlugin provides import ID suggestions (optional capability)
type ImportHelperPluginServer interface {
	GetImportSuggestions(context.Context, *ImportSuggestionsRequest) (*ImportSuggestionsResponse, error)
	mustEmbedUnimplementedImportHelperPluginServer()
}

// UnimplementedImportHelperPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportHelperPluginServer struct{}

func (UnimplementedImportHelperPluginServer) GetImportSuggestions(context.Context, *ImportSuggestionsRequest) (*ImportSuggestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImportSuggestions not implemented")
}
func (UnimplementedImportHelperPluginServer) mustEmbedUnimplementedImportHelperPluginServer() {}
func (UnimplementedImportHelperPluginServer) testEmbeddedByValue()                            {}

// UnsafeImportHelperPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportHelperPluginServer will
// result in compilation errors.
type UnsafeImportHelperPluginServer interface {
	mustEmbedUnimplementedImportHelperPluginServer()
}

func RegisterImportHelperPluginServer(s grpc.ServiceRegistrar, srv ImportHelperPluginServer) {
	// If the following call pancis, it indicates UnimplementedImportHelperPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImportHelperPlugin_ServiceDesc, srv)
}

func _ImportHelperPlugin_GetImportSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportHelperPluginServer).GetImportSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportHelperPlugin_GetImportSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportHelperPluginServer).GetImportSuggestions(ctx, req.(*ImportSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportHelperPlugin_ServiceDesc is the grpc.ServiceDesc for ImportHelperPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportHelperPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p5.plugin.v0.ImportHelperPlugin",
	HandlerType: (*ImportHelperPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImportSuggestions",
			Handler:    _ImportHelperPlugin_GetImportSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugins/proto/plugin.proto",
}

const (
	ResourceOpenerPlugin_GetSupportedOpenTypes_FullMethodName = "/p5.plugin.v0.ResourceOpenerPlugin/GetSupportedOpenTypes"
	ResourceOpenerPlugin_OpenResource_FullMethodName          = "/p5.plugin.v0.ResourceOpenerPlugin/OpenResource"
)

// ResourceOpenerPluginClient is the client API for ResourceOpenerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ResourceOpenerPlugin provides resource opening capabilities (optional capability)
// Plugins can open resources in a browser or launch an alternate screen program (e.g., k9s)
type ResourceOpenerPluginClient interface {
	// GetSupportedOpenTypes returns regex patterns for resource types this plugin can open
	GetSupportedOpenTypes(ctx context.Context, in *SupportedOpenTypesRequest, opts ...grpc.CallOption) (*SupportedOpenTypesResponse, error)
	// OpenResource returns the action to open a specific resource
	OpenResource(ctx context.Context, in *OpenResourceRequest, opts ...grpc.CallOption) (*OpenResourceResponse, error)
}

type resourceOpenerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceOpenerPluginClient(cc grpc.ClientConnInterface) ResourceOpenerPluginClient {
	return &resourceOpenerPluginClient{cc}
}

func (c *resourceOpenerPluginClient) GetSupportedOpenTypes(ctx context.Context, in *SupportedOpenTypesRequest, opts ...grpc.CallOption) (*SupportedOpenTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupportedOpenTypesResponse)
	err := c.cc.Invoke(ctx, ResourceOpenerPlugin_GetSupportedOpenTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceOpenerPluginClient) OpenResource(ctx context.Context, in *OpenResourceRequest, opts ...grpc.CallOption) (*OpenResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResourceResponse)
	err := c.cc.Invoke(ctx, ResourceOpenerPlugin_OpenResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceOpenerPluginServer is the server API for ResourceOpenerPlugin service.
// All implementations must embed UnimplementedResourceOpenerPluginServer
// for forward compatibility.
//
// ResourceOpenerPlugin provides resource opening capabilities (optional capability)
// Plugins can open resources in a browser or launch an alternate screen program (e.g., k9s)
type ResourceOpenerPluginServer interface {
	// GetSupportedOpenTypes returns regex patterns for resource types this plugin can open
	GetSupportedOpenTypes(context.Context, *SupportedOpenTypesRequest) (*SupportedOpenTypesResponse, error)
	// OpenResource returns the action to open a specific resource
	OpenResource(context.Context, *OpenResourceRequest) (*OpenResourceResponse, error)
	mustEmbedUnimplementedResourceOpenerPluginServer()
}

// UnimplementedResourceOpenerPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceOpenerPluginServer struct{}

func (UnimplementedResourceOpenerPluginServer) GetSupportedOpenTypes(context.Context, *SupportedOpenTypesRequest) (*SupportedOpenTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedOpenTypes not implemented")
}
func (UnimplementedResourceOpenerPluginServer) OpenResource(context.Context, *OpenResourceRequest) (*OpenResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenResource not implemented")
}
func (UnimplementedResourceOpenerPluginServer) mustEmbedUnimplementedResourceOpenerPluginServer() {}
func (UnimplementedResourceOpenerPluginServer) testEmbeddedByValue()                              {}

// UnsafeResourceOpenerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceOpenerPluginServer will
// result in compilation errors.
type UnsafeResourceOpenerPluginServer interface {
	mustEmbedUnimplementedResourceOpenerPluginServer()
}

func RegisterResourceOpenerPluginServer(s grpc.ServiceRegistrar, srv ResourceOpenerPluginServer) {
	// If the following call pancis, it indicates UnimplementedResourceOpenerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceOpenerPlugin_ServiceDesc, srv)
}

func _ResourceOpenerPlugin_GetSupportedOpenTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportedOpenTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceOpenerPluginServer).GetSupportedOpenTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceOpenerPlugin_GetSupportedOpenTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceOpenerPluginServer).GetSupportedOpenTypes(ctx, req.(*SupportedOpenTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceOpenerPlugin_OpenResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceOpenerPluginServer).OpenResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceOpenerPlugin_OpenResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceOpenerPluginServer).OpenResource(ctx, req.(*OpenResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceOpenerPlugin_ServiceDesc is the grpc.ServiceDesc for ResourceOpenerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceOpenerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p5.plugin.v0.ResourceOpenerPlugin",
	HandlerType: (*ResourceOpenerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupportedOpenTypes",
			Handler:    _ResourceOpenerPlugin_GetSupportedOpenTypes_Handler,
		},
		{
			MethodName: "OpenResource",
			Handler:    _ResourceOpenerPlugin_OpenResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugins/proto/plugin.proto",
}
