#!/usr/bin/env bash
# Release script using svu and goreleaser (managed via go.mod tools)
# Builds locally and generates CHANGELOG.md - no GitHub token required
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
DRY_RUN=false
FORCE_VERSION=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --version)
            FORCE_VERSION="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --dry-run      Show what would happen without making changes"
            echo "  --version VER  Force a specific version (e.g., v1.2.3)"
            echo "  -h, --help     Show this help message"
            echo ""
            echo "Output:"
            echo "  - Binaries in ./dist/"
            echo "  - CHANGELOG.md updated with release notes"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Check for uncommitted changes
if [[ -n $(git status --porcelain) ]]; then
    echo -e "${RED}Error: You have uncommitted changes${NC}"
    git status --short
    exit 1
fi

# Get version using go tool
if [[ -n "$FORCE_VERSION" ]]; then
    VERSION="$FORCE_VERSION"
else
    VERSION=$(go tool svu next)
fi

CURRENT_VERSION=$(go tool svu current 2>/dev/null || echo "v0.0.0")

echo -e "${GREEN}Current version:${NC} $CURRENT_VERSION"
echo -e "${GREEN}Next version:${NC}    $VERSION"

if [[ "$CURRENT_VERSION" == "$VERSION" ]]; then
    echo -e "${YELLOW}No version bump detected. Use conventional commits (feat:, fix:, etc.) or --version flag${NC}"
    exit 0
fi

if $DRY_RUN; then
    echo ""
    echo -e "${YELLOW}=== DRY RUN ===${NC}"
    echo ""
    echo "Would create tag: $VERSION"
    echo "Would build binaries to ./dist/"
    echo "Would update CHANGELOG.md"
    exit 0
fi

# Confirm release
echo ""
read -p "Release $VERSION? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

# Create tag
echo -e "${GREEN}Creating tag $VERSION...${NC}"
git tag -a "$VERSION" -m "Release $VERSION"

# Run goreleaser (builds locally, generates changelog in dist/)
echo -e "${GREEN}Building release...${NC}"
go tool goreleaser release --clean --skip=publish

# Update CHANGELOG.md from goreleaser output
echo -e "${GREEN}Updating CHANGELOG.md...${NC}"
if [[ -f dist/CHANGELOG.md ]]; then
    # Strip the "## Changelog" header from goreleaser output, keep just the content
    RELEASE_NOTES=$(sed '1{/^## Changelog$/d;}' dist/CHANGELOG.md)
    
    # Create new changelog content
    echo "# Changelog" > CHANGELOG.md.tmp
    echo "" >> CHANGELOG.md.tmp
    echo "## $VERSION" >> CHANGELOG.md.tmp
    echo "" >> CHANGELOG.md.tmp
    echo "$RELEASE_NOTES" >> CHANGELOG.md.tmp
    
    # Append existing changelog content (skip header if present)
    if [[ -f CHANGELOG.md ]]; then
        echo "" >> CHANGELOG.md.tmp
        if head -1 CHANGELOG.md | grep -q "^# Changelog"; then
            tail -n +3 CHANGELOG.md >> CHANGELOG.md.tmp
        else
            cat CHANGELOG.md >> CHANGELOG.md.tmp
        fi
    fi
    
    mv CHANGELOG.md.tmp CHANGELOG.md
    echo -e "${GREEN}CHANGELOG.md updated${NC}"
else
    echo -e "${YELLOW}Warning: No changelog generated by goreleaser${NC}"
fi

echo ""
echo -e "${GREEN}Release $VERSION complete!${NC}"
echo ""
echo "Artifacts:"
echo "  - Binaries: ./dist/"
echo "  - Changelog: CHANGELOG.md"
echo ""
echo "Next steps:"
echo "  1. Review and commit: git add CHANGELOG.md && git commit --amend --no-edit"
echo "  2. Push the tag: git push origin $VERSION"
